ALTER TABLE users
    ADD COLUMN IF NOT EXISTS name VARCHAR(150) NOT NULL,
    ADD COLUMN IF NOT EXISTS email VARCHAR(180) NOT NULL,
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS role VARCHAR(50) NOT NULL DEFAULT 'admin',
    ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
